name: Pipeline Test

on:
  push:
    branches:
    - main
    paths:
    - project/**

jobs:
  pipeline-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Set up Python
      uses: actions/setup-python@v4
      with: 
        python-version: 3.11

    - name: Test Pipeline
      run: |
        ./project/tests.sh